### ISSUE TITLE
Can't open any of my EXRs generated from Blender

### ISSUE THREAD

**Issue by riouxr** [afichet/openexr-viewer#51]
**Describe the bug**

**To Reproduce**
Open attached file

**Expected behavior**
My image
[Uploading 138D-440_Lighting_v0001_BG.1039.zip…]()

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by afichet** [comment]
Hi,

I cannot download the sample image you've provided.
Could you try reuploading it?

Cheers.

**Comment by riouxr** [comment]
Try from her please: https://www.dropbox.com/scl/fi/v23z4yzq1pig4qgen1cv1/138D-440_Lighting_v0001_BG.1039.exr?rlkey=xx0prwqmg2ijzpvx5rsu5i56i&dl=0

**Comment by afichet** [comment]
I can open the image you've sent me with v0.6.1.
Since there is no default RGB layer set, the viewer won't open any layer or layer set by default. You can choose to open one (in this case in `BG.Combined` or `BG.Noisy Image`) by double-clicking on the RGBA layer group in the Layer list in the bottom right.

Is that the issue you had?

**Comment by riouxr** [comment]
Doh! I didn't try to double-click. I just clicked on the different layers. Any particular reason why we need to double click?

**Comment by afichet** [comment]
Great!
The double click choice is to replicate the behaviour of file browsers. Also have planned to include support for spectral / bispectral images, which can be taxing on the hardware. The double click mitigates accidental opening and processing of such layer groups.
